### ISSUE TITLE
Connection refused while invoking Server Function

### ISSUE THREAD

**Issue by algoexpert12** [mlrun/mlrun#2102]
function_address = serving_fn.deploy()

> 2022-07-04 13:01:14,758 [debug] Auto mount disabled due to user selection (auto_mount_type=none)
> 2022-07-04 13:01:14,760 [info] Starting remote function deploy
2022-07-04 13:01:15  (info) Deploying function
2022-07-04 13:01:15  (info) Building
2022-07-04 13:01:15  (info) Staging files and preparing base images
2022-07-04 13:01:15  (info) Building processor image
2022-07-04 13:01:46  (info) Build complete
2022-07-04 13:01:46  (info) Cleaning up before deployment
2022-07-04 13:01:46  (info) Function already exists, deleting function containers
2022-07-04 13:01:50  (info) Function deploy complete
> 2022-07-04 13:01:50,813 [info] successfully deployed function: {'internal_invocation_urls': ['172.17.0.5:8080'], 'external_invocation_urls': ['127.0.0.1:58222']}
> 2022-07-04 13:01:50,816 [debug] saving function: serving, tag: 

-------------------------------------------------------------------

print (f'The address for the function is {function_address} \n')
​
!wget $function_address
The address for the function is http://127.0.0.1:58222/ 

--2022-07-04 13:02:01--  http://127.0.0.1:58222/
Connecting to 127.0.0.1:58222... failed: Connection refused.

**Comment by mashirali** [comment]
I have the same issue!!!!

**Comment by quaark** [comment]
@algoexpert12 When deploying a nuclio serving function without an ingress controller, you get two points of access:
1. Internal Invocation URL - the internal k8s cluster IP for the service hosting the function.
2. External Invocation URL - the node port exposed on the host machine of the k8s cluster which is mapped to said service.

As the External Invocation URL is localhost, this means localhost on the host machine of the cluster. From there, that access point should be available.
In order to invoke the function from within the jupyter notebook, as you are trying to do, you should use the internal invocation url - `172.17.0.5:8080` as the jupyter pod is within the k8s cluster.

**Comment by mashirali** [comment]
OSError                                   Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_4200\1376486452.py in <cell line: 1>()
----> 1 serving_fn.invoke("/v2/models/cancer-classifier/infer", body=my_data)

~\anaconda3\lib\site-packages\mlrun\runtimes\function.py in invoke(self, path, body, method, headers, dashboard, force_external_address, auth_info)
    829             resp = requests.request(method, path, headers=headers, **kwargs)
    830         except OSError as err:
--> 831             raise OSError(f"error: cannot run function at url {path}, {err}")
    832         if not resp.ok:
    833             raise RuntimeError(f"bad function response {resp.status_code}: {resp.text}")

**Comment by mashirali** [comment]
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

**Comment by Tankilevitch** [comment]
Hey @mashirali, which installation guide did you use? kubernetes or docker compose?

**Comment by mashirali** [comment]
Hey @Tankilevitch i am following guide via docker compose.

**Comment by haristimuno05** [comment]
Hi, I'm following the quick-start lab en when I execute `serving_fn.invoke("/v2/models/cancer-classifier/infer", body=my_data)` I have the same error, some idea @Tankilevitch @mashirali @algoexpert12 ?

**Comment by harishgawade1999** [comment]
I am also getting same error. please guide us for next.

**Comment by mashirali** [comment]
Try using the kubernetes based deployment. I hope.your error will be resolved then.

**Comment by mashirali** [comment]
First you should try kubernetes deployment as in my scenerio it worked. After that try checking if those ports are free/unallocated then you can get the positive response. In each try make sure to clear function from nuclio.

**Comment by mashirali** [comment]
Also if you share the code snippet, i can see that in details then

**Comment by harishgawade1999** [comment]
Hello. Thank you for suggestion. But I'm looking for open source tools to manage mlops lifecycle. so because of that I'm deploying with docker. I have raised same issue on Stackoverflow and here is its link. u can have a look over there. 
https://stackoverflow.com/questions/73945466/connectionrefusederror-errno-111-connection-refused-mlrun

**Comment by harishgawade1999** [comment]
> Try using the kubernetes based deployment. I hope your error will be resolved then. Also reset your project again before running by making sure you delete the nuclio functions. Then run the script again.

is this approach open source?

**Comment by harishgawade1999** [comment]
> Hi, I'm following the quick-start lab en when I execute `serving_fn.invoke("/v2/models/cancer-classifier/infer", body=my_data)` I have the same error, some idea @Tankilevitch @mashirali @algoexpert12 ?

Hello...Have you solved this issue. if yes, then how?

**Comment by haristimuno05** [comment]
> > Hi, I'm following the quick-start lab en when I execute `serving_fn.invoke("/v2/models/cancer-classifier/infer", body=my_data)` I have the same error, some idea @Tankilevitch @mashirali @algoexpert12 ?
> 
> Hello...Have you solved this issue. if yes, then how?

Same problem

**Comment by harishgawade1999** [comment]
> > > Hi, I'm following the quick-start lab en when I execute `serving_fn.invoke("/v2/models/cancer-classifier/infer", body=my_data)` I have the same error, some idea @Tankilevitch @mashirali @algoexpert12 ?
> > 
> > 
> > Hello...Have you solved this issue. if yes, then how?
> 
> Same problem

Havent u solved this issue? and are u trying to solve it?

**Comment by quaark** [comment]
@haristimuno05 , @harishgawade1999 - We have fixed the issue and it will be released as part of MLRun 1.2.0.
For now, you can modify the docker-compose file as it was modified in the fix PR - https://github.com/mlrun/mlrun/pull/2422, and that should work.

**Comment by haristimuno05** [comment]
> @haristimuno05 , @harishgawade1999 - We have fixed the issue and it will be released as part of MLRun 1.2.0. For now, you can modify the docker-compose file as it was modified in the fix PR - #2422, and that should work.

Thanks @quaark, I have been testing the solutions but didn't work in my case running the quick start tutorial in Jupyter.
![Captura de Pantalla 2022-10-18 a la(s) 10 09 38 a m](https://user-images.githubusercontent.com/52431527/196470172-26bae953-a41b-4321-a462-2f17912589f5.png)

**Comment by harishgawade1999** [comment]
> > @haristimuno05 , @harishgawade1999 - We have fixed the issue and it will be released as part of MLRun 1.2.0. For now, you can modify the docker-compose file as it was modified in the fix PR - #2422, and that should work.
> 
> Thanks @quaark, I have been testing the solutions but didn't work in my case running the quick start tutorial in Jupyter. ![Captura de Pantalla 2022-10-18 a la(s) 10 09 38 a m](https://user-images.githubusercontent.com/52431527/196470172-26bae953-a41b-4321-a462-2f17912589f5.png)
> 
> ![Captura de Pantalla 2022-10-18 a la(s) 10 11 46 a m](https://user-images.githubusercontent.com/52431527/196470652-ecd008e3-0bb8-4d27-bb92-49ab0cebd81d.png)

I'm also getting same error after doing changes too.

**Comment by harishgawade1999** [comment]
Hello Im still getting same error so please can anyone help me?

**Comment by harishgawade1999** [comment]
> 

When it will be released?

**Comment by harishgawade1999** [comment]
> MLRun 1.2.0



> 

msm

**Comment by harishgawade1999** [comment]
> @haristimuno05 , @harishgawade1999 - We have fixed the issue and it will be released as part of MLRun 1.2.0. For now, you can modify the docker-compose file as it was modified in the fix PR - #2422, and that should work.

Hello...When it will be released?

**Comment by liranbg** [comment]
> > @haristimuno05 , @harishgawade1999 - We have fixed the issue and it will be released as part of MLRun 1.2.0. For now, you can modify the docker-compose file as it was modified in the fix PR - #2422, and that should work.
> 
> Hello...When it will be released?

We are on the last mile. stay tuned! you will get notified by Github if you star the project :)

**Comment by Pritamchaudhari29** [comment]
Hi, I am also facing the same issue as @harishgawade1999 getting. I am also using MLRun with Docker. But after running the codes given in MLRun tutorials, one thing noticed that there is problem in deployment step. Though deployment code runs successfully, but  it doesn't shows on nuclio and MLRun UI. It has to show that deployment part on nuclio and MLRun UI. So I guess deployment is not running successfully. And that's why Invoke issue is occurring there, as deployment step is incomplete. Is I am right? Or yes, then what can do for deployment? What's the issue in the provided code for deployment?

**Comment by Pritamchaudhari29** [comment]
@liranbg , @quaark , @mashirali  Can you help me in above case please? I am struggling with it from too many days, so.

**Comment by harishgawade1999** [comment]
> 

When new version will be relesed?

**Comment by harishgawade1999** [comment]
> Hi everyone here in the issue, We've given a hard push on this to find all the issues ultimately causing the behaviour you all are facing with the docker compose deployment. We will merge the PR and release a new mlrun version very soon which will fix this. Stay tuned :)
> 
> PS: If you need this now, you are welcome to manually use the changes in the above PR, but please read the description and the relevant caveat in it.

When New Version will be released?

**Comment by j0terry** [comment]
I have probably the same issue with first mlrun tutorial sample ('01-mlrun-basics.ipynb'). It seems as big blocker.

**Comment by j0terry** [comment]
@yaronha , please can you help with the issue? It seems as bigger problem, see this discussion.

**Comment by Tankilevitch** [comment]
> I have probably the same issue with first mlrun tutorial sample ('01-mlrun-basics.ipynb'). It seems as big blocker.

Should be resolved in 1.2.0

**Comment by j0terry** [comment]
@Tankilevitch, the issue in version '1.2.0' still exist, see #2716

**Comment by harishgawade1999** [comment]
> @Tankilevitch, the issue in version '1.2.0' still exist, see #2716

I'm also getting "max retries error" in '1.2.0'

**Comment by yaronha** [comment]
> @yaronha , please can you help with the issue? It seems as bigger problem, see this discussion.

@j0terry it does work in 1.2.0 from what I saw, I'm now testing all the scenarios and adding some simplification 

usage example (in unix):
```
export HOST_IP=$(ip route get 1.2.3.4 | awk '{print $7}')
export SHARED_DIR=~/mlrun-data 
export TAG=1.2.0
mkdir $(SHARED_DIR) -p
docker-compose -f compose.yaml up -d
```

**Comment by j0terry** [comment]
@yaronha , I tested it with 'compose.with-jupyter.yaml'

`docker-compose -f "c:\MLRun\compose.with-jupyter.yaml" up`

I am going to test it with different IDE.

**Comment by harishgawade1999** [comment]
> @yaronha , I tested it with 'compose.with-jupyter.yaml'
> 
> `docker-compose -f "c:\MLRun\compose.with-jupyter.yaml" up`
> 
> I am going to test it with different IDE.

is that works?

**Comment by harishgawade1999** [comment]
> > @yaronha , please can you help with the issue? It seems as bigger problem, see this discussion.
> 
> @j0terry it does work in 1.2.0 from what I saw, I'm now testing all the scenarios and adding some simplification
> 
> usage example (in unix):
> 
> ```
> export HOST_IP=$(ip route get 1.2.3.4 | awk '{print $7}')
> export SHARED_DIR=~/mlrun-data 
> export TAG=1.2.0
> mkdir $(SHARED_DIR) -p
> docker-compose -f compose.yaml up -d
> ```

for windows, what will be its syntax?

**Comment by j0terry** [comment]
@yaronha , @harishgawade1999 I tested:

- only compose.yaml (without Jupyter with MLRun==1.2.0)
- IDE PyCharm 2022.3
- I rewrite '01-mlrun-basics.ipynb' to 'mlrun_basic.py'
- I have to install to addition python packages 'plotly, graphviz'

and finally I got the same issue with '**Max retries exceeded with url**' (It seems as license limit for MLRun community edition)

**Comment by george0st** [comment]
It seems, that I have the same mistake in last part of tutorial.

**Comment by yaronha** [comment]
@j0terry @harishgawade1999 you cannot use 127.0.0.1 (local address), since it will be local to the client container, you need to use the host address which will allow routing to the other containers.. in windows you can see that with `ipconfig` , best to choose a stable address (not using DHCP, e.g. the WSL address), this is clearly explained in the documentation:

`Your HOST_IP address can be found using the ipconfig shell command, it is recommended to select an address that does not change dynamically (for example the IP of the vEthernet interface).`

**Comment by harishgawade1999** [comment]
> @j0terry @harishgawade1999 you cannot use 127.0.0.1 (local address), since it will be local to the client container, you need to use the host address which will allow routing to the other containers.. in windows you can see that with `ipconfig` , best to choose a stable address (not using DHCP, e.g. the WSL address), this is clearly explained in the documentation:
> 
> `Your HOST_IP address can be found using the ipconfig shell command, it is recommended to select an address that does not change dynamically (for example the IP of the vEthernet interface).`
> 
> for PowerShell:
> 
> `Your HOST_IP address can be found using the Get-NetIPConfiguration cmdlet, it is recommended to select an address that does not change dynamically (for example the IP of the vEthernet interface).`

yess...im using ip address of wi-fi...is that causing this error?

**Comment by harishgawade1999** [comment]
> @j0terry @harishgawade1999 you cannot use 127.0.0.1 (local address), since it will be local to the client container, you need to use the host address which will allow routing to the other containers.. in windows you can see that with `ipconfig` , best to choose a stable address (not using DHCP, e.g. the WSL address), this is clearly explained in the documentation:
> 
> `Your HOST_IP address can be found using the ipconfig shell command, it is recommended to select an address that does not change dynamically (for example the IP of the vEthernet interface).`
> 
> for PowerShell:
> 
> `Your HOST_IP address can be found using the Get-NetIPConfiguration cmdlet, it is recommended to select an address that does not change dynamically (for example the IP of the vEthernet interface).`

Can u please drop ur yaml file here...it will be really helpful.

**Comment by yaronha** [comment]
> > @j0terry @harishgawade1999 you cannot use 127.0.0.1 (local address), since it will be local to the client container, you need to use the host address which will allow routing to the other containers.. in windows you can see that with `ipconfig` , best to choose a stable address (not using DHCP, e.g. the WSL address), this is clearly explained in the documentation:
> > `Your HOST_IP address can be found using the ipconfig shell command, it is recommended to select an address that does not change dynamically (for example the IP of the vEthernet interface).`
> > for PowerShell:
> > `Your HOST_IP address can be found using the Get-NetIPConfiguration cmdlet, it is recommended to select an address that does not change dynamically (for example the IP of the vEthernet interface).`
> 
> Can u please drop ur yaml file here...it will be really helpful.

See the documentation https://docs.mlrun.org/en/stable/install/local-docker.html there is a `download` link near each and also a show/expand box to view the YAMLs

**Comment by harishgawade1999** [comment]
> > > @j0terry @harishgawade1999 you cannot use 127.0.0.1 (local address), since it will be local to the client container, you need to use the host address which will allow routing to the other containers.. in windows you can see that with `ipconfig` , best to choose a stable address (not using DHCP, e.g. the WSL address), this is clearly explained in the documentation:
> > > `Your HOST_IP address can be found using the ipconfig shell command, it is recommended to select an address that does not change dynamically (for example the IP of the vEthernet interface).`
> > > for PowerShell:
> > > `Your HOST_IP address can be found using the Get-NetIPConfiguration cmdlet, it is recommended to select an address that does not change dynamically (for example the IP of the vEthernet interface).`
> > 
> > 
> > Can u please drop ur yaml file here...it will be really helpful.
> 
> See the documentation https://docs.mlrun.org/en/stable/install/local-docker.html there is a `download` link near each and also a show/expand box to view the YAMLs

I'm using the same...we don't have to update anything in this yaml?

**Comment by jnh277** [comment]
This still seems to be an issue? I was attempting to do the tutorials and came across this same problem? or is there a work around?
