### ISSUE TITLE
[Bug]: Error - the server could not find the requested resource     ...//nuclio/pkg/platform/kube/functionres/lazy.go:757

### ISSUE THREAD

**Issue by harishgawade1999** [mlrun/mlrun#3387]
### MLRun Version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the latest version of MLRun CE.

### **_Reproducible Example_**

```python
I'm working with following Demo:-

https://docs.mlrun.org/en/stable/tutorial/01-mlrun-basics.html
```

### **_Issue Description_**

2023-04-06 11:11:09,025 [warning] it is recommended to use k8s secret (specify secret_name), specifying the aws_access_key/aws_secret_key directly is unsafe
> 2023-04-06 11:11:09,030 [info] Starting remote function deploy
2023-04-06 11:11:09  (info) Deploying function
2023-04-06 11:11:09  (info) Building
2023-04-06 11:11:09  (info) Staging files and preparing base images
2023-04-06 11:11:09  (info) Building processor image
Failed to deploy. Details:

> 2023-04-06 11:16:55,264 [error] Nuclio function failed to deploy: {'function_state': 'error'}
---------------------------------------------------------------------------
RunError                                  Traceback (most recent call last)
<ipython-input-20-38c4d06add9b> in <module>
----> 1 project.deploy_function(serving_fn)

/opt/conda/lib/python3.8/site-packages/mlrun/projects/project.py in deploy_function(self, function, dashboard, models, env, tag, verbose, builder_env, mock)
   2315         :param mock:        deploy mock server vs a real Nuclio function (for local simulations)
   2316         """
-> 2317         return deploy_function(
   2318             function,
   2319             dashboard=dashboard,

/opt/conda/lib/python3.8/site-packages/mlrun/projects/operations.py in deploy_function(function, dashboard, models, env, tag, verbose, builder_env, project_object, mock)
    343             )
    344 
--> 345         address = function.deploy(
    346             dashboard=dashboard, tag=tag, verbose=verbose, builder_env=builder_env
    347         )

/opt/conda/lib/python3.8/site-packages/mlrun/runtimes/serving.py in deploy(self, dashboard, project, tag, verbose, auth_info, builder_env)
    621             logger.info(f"deploy root function {self.metadata.name} ...")
    622 
--> 623         return super().deploy(
    624             dashboard, project, tag, verbose, auth_info, builder_env=builder_env
    625         )

/opt/conda/lib/python3.8/site-packages/mlrun/runtimes/function.py in deploy(self, dashboard, project, tag, verbose, auth_info, builder_env)
    550             self.status = data["data"].get("status")
    551             self._update_credentials_from_remote_build(data["data"])
--> 552             self._wait_for_function_deployment(db, verbose=verbose)
    553 
    554             # NOTE: on older mlrun versions & nuclio versions, function are exposed via NodePort

/opt/conda/lib/python3.8/site-packages/mlrun/runtimes/function.py in _wait_for_function_deployment(self, db, verbose)
    620         if state != "ready":
    621             logger.error("Nuclio function failed to deploy", function_state=state)
--> 622             raise RunError(f"function {self.metadata.name} deployment failed")
    623 
    624     @min_nuclio_versions("1.5.20", "1.6.10")

**RunError: function serving deployment failed**

### **_Expected Behavior_**

It should get deployed without any error. for now, its showing following error on Nuclio .

[16:41:09.104]  (I)  Deploying function   [requestID: "nuclio-dashboard-6677788464-nbkwj/LNF6lalZGc-000616"] 
 [16:41:09.107]  (I)  Building   [builderKind: "kaniko", versionInfo: "Label: 1.11.8, Git commit: 534ce403e0b23439ddc0b6de76e056a01a435c0c, OS: linux, Arch: amd64, Go version: go1.17.10"] 
 [16:41:09.121]  (I)  Staging files and preparing base images    
 [16:41:09.123]  (I)  Building processor image   [registryURL: "registry.hub.docker.com/harishgawade199", taggedImageName: "processor-quick-tutorial-jovyan-serving:latest"] 
 [16:46:54.685]  (I)  Build complete   [image: "processor-quick-tutorial-jovyan-serving:latest"] 
 [16:46:55.035]  (W)  Function creation failed, updating function status   [errorStack: "
Error - NuclioFunction in error state:

Error - the server could not find the requested resource
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:757

Call stack:
Failed to create resource
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:757
Failed to create/update HPA
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:230
Failed to create/update function
    .../platform/kube/controller/nucliofunction.go:213

    ...//nuclio/pkg/platform/kube/client/deployer.go:615

Call stack:
NuclioFunction in error state:

Error - the server could not find the requested resource
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:757

Call stack:
Failed to create resource
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:757
Failed to create/update HPA
    ...//nuclio/pkg/platform/kube/functionres/lazy.go:230
Failed to create/update function
    .../platform/kube/controller/nucliofunction.go:213

    ...//nuclio/pkg/platform/kube/client/deployer.go:615
Failed to wait for function readiness.

Pod logs:

* nuclio-quick-tutorial-jovyan-serving-995c8bf6f-79sxn
Failed to read logs: container "nuclio" in pod "nuclio-quick-tutorial-jovyan-serving-995c8bf6f-79sxn" is waiting to start: ContainerCreating

* Warning events:

    ...//nuclio/pkg/platform/kube/client/deployer.go:155
", requestID: "nuclio-dashboard-6677788464-nbkwj/LNF6lalZGc-000616"] 

### **_Installation OS_**

Windows

### **_Installation Method_**

Kubernetes

### **_Python Version_**

3.8

### **_MLRun Version_**

Mlrun CE 1.2.1

### **_Additional Information_**

I'm using Docker, Kubectl and helm to work with mlrun CE.

**Comment by Tankilevitch** [comment]
Hey @harishgawade1999, This bug was resolved in 1.3.0 version.
Please follow https://docs.mlrun.org/en/latest/install/local-docker.html for installing the MLRun with the latest 1.3.0 as well as updating your client to 1.3.0. 
Let me know if that solved your issue

**Comment by harishgawade1999** [comment]
> Hey @harishgawade1999, This bug was resolved in 1.3.0 version. Please follow https://docs.mlrun.org/en/latest/install/local-docker.html for installing the MLRun with the latest 1.3.0 as well as updating your client to 1.3.0. Let me know if that solved your issue

How can i use v1.3.0 for mlrun with kubernetes approach...for now, if i'm following steps as mentioned here " https://docs.mlrun.org/en/latest/install/kubernetes.html". and with this version im using. im getting same error. please help me with that...

**Comment by harishgawade1999** [comment]
> Hey @harishgawade1999, This bug was resolved in 1.3.0 version. Please follow https://docs.mlrun.org/en/latest/install/local-docker.html for installing the MLRun with the latest 1.3.0 as well as updating your client to 1.3.0. Let me know if that solved your issue

### Hey @Tankilevitch 
The error persists even after I installed the most recent version of mlrun (1.3.0) with Kubernetes.
